### ISSUE TITLE
Fancy repo and project name

### ISSUE THREAD

**Issue by j-pawlowski** [appmazing/expressify-express-starterkit#9]
How about getting a nice sounding name for this project?

My type: **Expresify**

@cypherq @archibold

**Comment by benedyktdryl** [comment]
So "Expres**s**ify" ;)

We can have like release name or something but for now, quite standard is just to have "starter/starter kit/boilerplate" in name.

@archibold what do you think?

**Comment by j-pawlowski** [comment]
**Expres**(s)**ify** was more about a project name. Repo name would look like this: **expressify-express-boilerplate** or **expressify-express-starterkit** or **expressify-express-kickstarter**

**Comment by benedyktdryl** [comment]
Would like to go with "expressify-express-starterkit" - we can stay with Expressify then.

**Comment by j-pawlowski** [comment]
👍
